services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TuPassword123*"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - sqlnet

  sql-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: sql-init
    depends_on:
      - sqlserver
    volumes:
      - ./init-db:/scripts
    entrypoint: >
      /bin/bash -c "
        sleep 15;
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P TuPassword123* -i /scripts/init.sql;
      "
    networks:
      - sqlnet

volumes:
  sql_data:

networks:
  sqlnet:

